config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  
  get 'services' => 'pages#services'
  get 'about' => 'pages#about'
  get 'gallery' => 'pages#gallery'
  get 'order' => 'pages#order'
  get 'contact' => 'pages#contact'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    
    def services
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About Us</title>
    <!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="css/styles.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
  </head>
  <body>
  
<div class="container-fluid">
  <div class="row">
  <div class="col-md-3">
	  <center><%= image_tag("logo.png", alt: 'responsive image', style:"height: 150px; width: 150px;") %></center>
	  </div>
    <div class="col-md-6">
     
     
     <nav class="navbar navbar-primary">
  <div class="container-fluid mainnav">
   	
    
    <ul class="nav nav-pills">
     
      <li><%= link_to 'Home', root_path, :class => "btn" %></li>
      <li><%= link_to 'Services', services_path, :class => "btn" %></li>
      <li  class="active"><a href="#">About Us</a></li>
      <li><%= link_to 'Gallery', gallery_path, :class => "btn" %></li>
      <li><%= link_to 'Order', order_path, :class => "btn" %></li>
      <li><a href="#">Forum</a></li>
      <li><%= link_to 'Contact Us', contact_path, :class => "btn" %></li>
      </ul>
	  
	  </div>
			</nav>
		
    </div>
	  <div class="col-md-3"></div>
	  <br />
	  <br />
	  <br />
	  <i>Phone:</i> 614-222-1234<br />
	  <i>email:</i> webmaster@lugnuts.io<br />
	  <i>Address:</i> 123 Main St. Columbus, Ohio 43212<br />
	
	</div>
	</div>



  
	  <div class="row">
		  <div class="col-md-3">
			  <h3>Testimonials:</h3>
			  <p><b>Lorem ipsum</b> dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. </p>
			  <p><b>Quisque volutpat </b>condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. </p>
			  <p><b>Nec ullamcorper sed enim</b>, eu ligula dolores per quisque imperdiet semper, purus donec suspendisse mauris placerat, fugit tellus. Luctus a urna diam viverra sit lorem, sem ac turpis, pellentesque ut commodo, diam at donec, pellentesque integer pede. Phasellus nec quis neque amet proin fringilla, hendrerit blandit. Et laoreet faucibus. Et sem orci. Pede mauris, porttitor libero mollis, iaculis amet ullamcorper in aliqua orci, amet massa nulla at consectetuer.</p>
		  </div>
		  
		  <div class="col-md-6">
		  
			  <h2>About Us...</h2>
			  
			  
		  	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. </p>

			<p>Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. </p>
					  	
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. </p>

			<p>Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. </p>
					  	
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. </p>

			<p>Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. </p>

					  	
		  </div>
		  
		  <div class="col-md-3">
			  <h3>Info Box...</h3>
			  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>

			<p>Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. </p>

			<p>Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. </p>
		  </div>
		  </div>
	  <div id="bottom">	
	  	<div class="row">
	  		<footer id="footer">
	  			<div class="container-fluid">
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
				</div>
			</footer>

	  	
	  </div>
		  </div>

  
  
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
	<script src="js/jquery-1.11.3.min.js"></script>

	<!-- Include all compiled plugins (below), or include individual files as needed --> 
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Untitled Document</title>
    <!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="css/styles.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
  </head>
  <body>
  
<div class="container-fluid">
  <div class="row">
  <div class="col-md-3">
	  <center><%= image_tag("logo.png", alt: 'responsive image', style:"height: 150px; width: 150px;") %></center>
	  </div>
    <div class="col-md-6">
     
     
     <nav class="navbar navbar-primary">
  <div class="container-fluid mainnav">
   	
    
    <ul class="nav nav-pills">
     
      <li><%= link_to 'Home', root_path, :class => "btn" %></li>
      <li><%= link_to 'Services', services_path, :class => "btn" %></li>
      <li><%= link_to 'About Us', about_path, :class => "btn" %></li>
      <li><%= link_to 'Gallery', gallery_path, :class => "btn" %></li>
      <li><%= link_to 'Order', order_path, :class => "btn" %></li>
      <li><a href="#">Forum</a></li>
      <li  class="active"><a href="#">Contact Us</a></li>
      </ul>
	  
	  </div>
			</nav>
		
    </div>
	  <div class="col-md-3"></div>
	  <br />
	  <br />
	  <br />
	  <i>Phone:</i> 614-222-1234<br />
	  <i>email:</i> webmaster@lugnuts.io<br />
	  <i>Address:</i> 123 Main St. Columbus, Ohio 43212<br />
	
	</div>
	</div>
		<div class="row">
			<center><h2>Contact Us...</h2></center>
	  </div>
	  <div class="row">
		  <div class="container col-md-6">
		  <div class="input-group">
  <span class="input-group-addon" id="sizing-addon2">Name:</span>
  <input type="text" class="form-control" placeholder="" aria-describedby="sizing-addon2">
</div>
  		 <div class="input-group"> 
  		 <span class="input-group-addon" id="sizing-addon1"> Email: </span> 
  <input type="text" class="form-control" placeholder="" aria-describedby="sizing-addon2">  
</div>
  <div class="input-group"> 
  		 <span class="input-group-addon" id="sizing-addon2">Phone:</span> 
  <input type="text" class="form-control" placeholder="" aria-describedby="sizing-addon2">  
</div>
	  </div>
	  
	  		<div class="container col-md-6">
	  		<div class="form-group">
  <span class="input-group-addon" id="sizing-addon3">Message:</span> 
  <textarea class="form-control" rows="3" id="comment"></textarea>
</div>
		  </div>
	  </div>
	  
	  



   <div id="bottom">	
	  	<div class="row">
	  		<footer id="footer">
	  			<div class="container-fluid">
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
				</div>
			</footer>

	  	
	  </div>
		  </div>

	  
  
  
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
	<script src="js/jquery-1.11.3.min.js"></script>

	<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lugnuts Automotive Wraps</title>
    <!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href="css/styles.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
  </head>
  <body>
  
<div class="container-fluid">
  <div class="row">
  <div class="col-md-3">
	  <center><%= image_tag("logo.png", alt: 'responsive image', style:"height: 150px; width: 150px;") %></center>
	  </div>
    <div class="col-md-6">
     
     
     <nav class="navbar navbar-primary">
  <div class="container-fluid mainnav">
   	
    
    <ul class="nav nav-pills">
     
      <li class="active"><a href="#">Home</a></li>
      <li><%= link_to 'Services', services_path, :class => "btn" %></li>
      <li><%= link_to 'About', about_path, :class => "btn" %></li>
      <li><%= link_to 'Gallery', gallery_path, :class => "btn" %></li>
      <li><%= link_to 'Order', order_path, :class => "btn" %></li>
      <li><a href="#">Forum</a></li>
      <li><%= link_to 'Contact Us', contact_path, :class => "btn" %></li>
      </ul>
	  
	  </div>
			</nav>
		
    </div>
	  <div class="col-md-3"></div>
	  <br />
	  <br />
	  <br />
	  <i>Phone:</i> 614-222-1234<br />
	  <i>email:</i> webmaster@lugnuts.io<br />
	  <i>Address:</i> 123 Main St. Columbus, Ohio 43212<br />
	
	</div>
	</div>



  
	  <div class="row">
		  <div class="col-md-3">
			  <h3>Testimonials:</h3>
			  <p><b>Lorem ipsum</b> dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. </p>
			  <p><b>Quisque volutpat </b>condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. </p>
			  <p><b>Nec ullamcorper sed enim</b>, eu ligula dolores per quisque imperdiet semper, purus donec suspendisse mauris placerat, fugit tellus. Luctus a urna diam viverra sit lorem, sem ac turpis, pellentesque ut commodo, diam at donec, pellentesque integer pede. Phasellus nec quis neque amet proin fringilla, hendrerit blandit. Et laoreet faucibus. Et sem orci. Pede mauris, porttitor libero mollis, iaculis amet ullamcorper in aliqua orci, amet massa nulla at consectetuer.</p>
		  </div>
		  
		  <div class="col-md-6">
		  
			  <h2>This is the intro...</h2>
			  
			  
<div class="embed-responsive embed-responsive-16by9">
 	<iframe width="560" height="315" src="https://www.youtube.com/embed/NBqmYVMbiI4" frameborder="0" allowfullscreen></iframe>
</div>

		  	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. </p>

			<p>Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. </p>

					  	
		  </div>
		  
		  <div class="col-md-3">
			  <h3>Info Box...</h3>
			  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>

			<p>Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. </p>

			<p>Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. </p>
		  </div>
		  </div>
	  <div id="bottom">	
	  	<div class="row">
	  		<footer id="footer">
	  			<div class="container-fluid">
	  				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
				</div>
			</footer>

	  	
	  </div>
		  </div>

  
  
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
	<script src="js/jquery-1.11.3.min.js"></script>

	<!-- Include all compiled plugins (below), or include individual files as needed --> 
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>